import { useEffect, useState } from 'react'
import {
  Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer,
  Scatter, ScatterChart, Tooltip, XAxis, YAxis, ZAxis,
} from 'recharts'
import Topbar from '../components/Topbar'
import SeverityBadge from '../components/SeverityBadge'
import { getAlerts } from '../api/client'
import type { AlertRecord, Severity } from '../types'

const SEVERITY_FILTERS: Array<Severity | 'All'> = ['All', 'Critical', 'Warning', 'Info']
const ALERT_SEVERITIES: Severity[] = ['Critical', 'Warning', 'Info']
const AXIS_STYLE = { fontSize: 11, fill: '#7B879A' }
const SEVERITY_COLOR: Record<Severity, string> = {
  Critical: '#C5293A',
  Warning: '#C77A12',
  Info: '#2E7BD6',
}

function dateKey(iso: string) {
  return new Date(iso).toISOString().slice(0, 10)
}

function shortDate(label: string) {
  return new Date(label).toLocaleDateString('en-IN', { day: '2-digit', month: 'short' })
}

function buildRouteData(alerts: AlertRecord[]) {
  const rows = new Map<string, { route: string; critical: number; warning: number; info: number }>()
  alerts.forEach((alert) => {
    const row = rows.get(alert.route) ?? { route: alert.route, critical: 0, warning: 0, info: 0 }
    row[alert.severity.toLowerCase() as 'critical' | 'warning' | 'info'] += 1
    rows.set(alert.route, row)
  })
  return Array.from(rows.values())
}

function buildTrendData(alerts: AlertRecord[]) {
  const rows = new Map<string, { date: string; critical: number; warning: number; info: number; total: number }>()
  alerts.forEach((alert) => {
    const key = dateKey(alert.time)
    const row = rows.get(key) ?? { date: key, critical: 0, warning: 0, info: 0, total: 0 }
    row[alert.severity.toLowerCase() as 'critical' | 'warning' | 'info'] += 1
    row.total += 1
    rows.set(key, row)
  })
  return Array.from(rows.values()).sort((a, b) => a.date.localeCompare(b.date)).slice(-14)
}

export default function AlertsPage() {
  const [alerts, setAlerts] = useState<AlertRecord[]>([])
  const [filter, setFilter] = useState<Severity | 'All'>('All')
  const [loading, setLoading] = useState(true)

  const routeData = buildRouteData(alerts)
  const trendData = buildTrendData(alerts)
  const mappedAlerts = alerts.filter((a) => a.lat != null && a.lon != null)
  const summary = {
    Critical: alerts.filter((a) => a.severity === 'Critical').length,
    Warning: alerts.filter((a) => a.severity === 'Warning').length,
    Info: alerts.filter((a) => a.severity === 'Info').length,
  }

  useEffect(() => {
    setLoading(true)
    getAlerts(filter === 'All' ? undefined : { severity: filter })
      .then(setAlerts)
      .finally(() => setLoading(false))
  }, [filter])

  return (
    <>
      <Topbar title="Alerts" subtitle="Threshold-violation alerts generated by the rule engine" />

      <div className="p-6 space-y-4">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
          {ALERT_SEVERITIES.map((severity) => (
            <button
              key={severity}
              onClick={() => setFilter(severity)}
              className="panel p-4 text-left hover:border-rail-blue/40 transition-colors"
            >
              <div className="flex items-center justify-between">
                <span className="label-eyebrow">{severity}</span>
                <span
                  className="h-2.5 w-2.5 rounded-full"
                  style={{ backgroundColor: SEVERITY_COLOR[severity] }}
                />
              </div>
              <p className="mt-2 font-display text-[26px] leading-none text-rail-navy">
                {summary[severity]}
              </p>
            </button>
          ))}
        </div>

        <div className="grid grid-cols-1 xl:grid-cols-2 gap-4">
          <div className="panel">
            <div className="panel-header">
              <p className="font-display font-medium text-[14px] text-rail-navy">Alert Map</p>
              <span className="label-eyebrow">GPS alert positions</span>
            </div>
            <div className="p-3 h-72">
              <ResponsiveContainer width="100%" height="100%">
                <ScatterChart>
                  <CartesianGrid strokeDasharray="3 3" stroke="#EEF1F5" />
                  <XAxis
                    type="number"
                    dataKey="lon"
                    name="Longitude"
                    tick={AXIS_STYLE}
                    domain={['auto', 'auto']}
                  />
                  <YAxis
                    type="number"
                    dataKey="lat"
                    name="Latitude"
                    tick={AXIS_STYLE}
                    domain={['auto', 'auto']}
                  />
                  <ZAxis type="number" dataKey="peak" range={[70, 230]} name="Value" />
                  <Tooltip
                    cursor={{ strokeDasharray: '3 3' }}
                    formatter={(value, name) => [value, name]}
                    labelFormatter={() => ''}
                  />
                  {ALERT_SEVERITIES.map((severity) => (
                    <Scatter
                      key={severity}
                      name={severity}
                      data={mappedAlerts.filter((a) => a.severity === severity)}
                      fill={SEVERITY_COLOR[severity]}
                    />
                  ))}
                </ScatterChart>
              </ResponsiveContainer>
            </div>
            <p className="px-4 pb-3 text-[11px] text-rail-steelLight">
              Plotted by longitude / latitude from the uploaded session GPS. A production map can replace
              this with railway route tiles when the map provider/API key is available.
            </p>
          </div>

          <div className="panel">
            <div className="panel-header">
              <p className="font-display font-medium text-[14px] text-rail-navy">Alerts by Route</p>
              <span className="label-eyebrow">stacked by severity</span>
            </div>
            <div className="p-3 h-72">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={routeData}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#EEF1F5" />
                  <XAxis dataKey="route" tick={AXIS_STYLE} />
                  <YAxis allowDecimals={false} tick={AXIS_STYLE} />
                  <Tooltip />
                  <Legend wrapperStyle={{ fontSize: 11 }} />
                  <Bar dataKey="critical" stackId="a" fill={SEVERITY_COLOR.Critical} name="Critical" />
                  <Bar dataKey="warning" stackId="a" fill={SEVERITY_COLOR.Warning} name="Warning" />
                  <Bar dataKey="info" stackId="a" fill={SEVERITY_COLOR.Info} name="Info" radius={[3, 3, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            </div>
          </div>
        </div>

        <div className="panel">
          <div className="panel-header">
            <p className="font-display font-medium text-[14px] text-rail-navy">Alert Trend</p>
            <span className="label-eyebrow">latest 14 active alert days</span>
          </div>
          <div className="p-3 h-56">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={trendData}>
                <CartesianGrid strokeDasharray="3 3" stroke="#EEF1F5" />
                <XAxis dataKey="date" tickFormatter={shortDate} tick={AXIS_STYLE} />
                <YAxis allowDecimals={false} tick={AXIS_STYLE} />
                <Tooltip labelFormatter={(v) => shortDate(v as string)} />
                <Line type="monotone" dataKey="total" stroke="#12365C" strokeWidth={2} dot={{ r: 3 }} name="Total" />
                <Line type="monotone" dataKey="critical" stroke={SEVERITY_COLOR.Critical} strokeWidth={1.8} dot={false} name="Critical" />
                <Line type="monotone" dataKey="warning" stroke={SEVERITY_COLOR.Warning} strokeWidth={1.8} dot={false} name="Warning" />
                <Line type="monotone" dataKey="info" stroke={SEVERITY_COLOR.Info} strokeWidth={1.8} dot={false} name="Info" />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </div>

        <div className="flex items-center gap-2">
          {SEVERITY_FILTERS.map((s) => (
            <button
              key={s}
              onClick={() => setFilter(s)}
              className={[
                'px-3 py-1.5 rounded-md text-[12.5px] font-medium border transition-colors',
                filter === s
                  ? 'bg-rail-navy text-white border-rail-navy'
                  : 'bg-white text-rail-steel border-rail-line hover:border-rail-blue/40',
              ].join(' ')}
            >
              {s}
            </button>
          ))}
        </div>

        <div className="panel">
          <div className="panel-header">
            <p className="font-display font-medium text-[14px] text-rail-navy">Alerts</p>
            <span className="label-eyebrow">{alerts.length} record(s)</span>
          </div>
          <div className="overflow-x-auto">
            <table className="w-full text-[13px]">
              <thead>
                <tr className="text-left text-rail-steelLight border-b border-rail-line">
                  <th className="px-4 py-2.5 font-medium">Time</th>
                  <th className="px-4 py-2.5 font-medium">Route</th>
                  <th className="px-4 py-2.5 font-medium">Train</th>
                  <th className="px-4 py-2.5 font-medium">Metric</th>
                  <th className="px-4 py-2.5 font-medium">Value (g)</th>
                  <th className="px-4 py-2.5 font-medium">Threshold (g)</th>
                  <th className="px-4 py-2.5 font-medium">Nearest KM</th>
                  <th className="px-4 py-2.5 font-medium">Severity</th>
                </tr>
              </thead>
              <tbody>
                {alerts.map((a) => (
                  <tr key={a.id} className="border-b border-rail-line last:border-0 hover:bg-rail-fog/60">
                    <td className="px-4 py-2.5 text-rail-steelLight font-mono text-[12px]">
                      {new Date(a.time).toLocaleString('en-IN')}
                    </td>
                    <td className="px-4 py-2.5 text-rail-navy font-medium">{a.route}</td>
                    <td className="px-4 py-2.5 font-mono text-rail-steel">{a.trainId}</td>
                    <td className="px-4 py-2.5 text-rail-steel capitalize">{a.metric}</td>
                    <td className="px-4 py-2.5 font-mono text-rail-steel">{a.peak.toFixed(1)}</td>
                    <td className="px-4 py-2.5 font-mono text-rail-steelLight">{a.threshold.toFixed(1)}</td>
                    <td className="px-4 py-2.5 font-mono text-rail-steelLight">
                      {a.nearestTrackFeatureKm != null ? `Km ${a.nearestTrackFeatureKm.toFixed(0)}` : '-'}
                    </td>
                    <td className="px-4 py-2.5"><SeverityBadge severity={a.severity} /></td>
                  </tr>
                ))}
                {alerts.length === 0 && !loading && (
                  <tr>
                    <td colSpan={8} className="px-4 py-8 text-center text-rail-steelLight">
                      No alerts for this filter.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </>
  )
}
