import { useEffect, useState } from 'react'
import Topbar from '../components/Topbar'
import SeverityBadge from '../components/SeverityBadge'
import { getAlerts } from '../api/client'
import type { AlertRecord, Severity } from '../types'

const SEVERITY_FILTERS: Array<Severity | 'All'> = ['All', 'Critical', 'Warning', 'Info']

export default function AlertsPage() {
  const [alerts, setAlerts] = useState<AlertRecord[]>([])
  const [filter, setFilter] = useState<Severity | 'All'>('All')
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    setLoading(true)
    getAlerts(filter === 'All' ? undefined : { severity: filter })
      .then(setAlerts)
      .finally(() => setLoading(false))
  }, [filter])

  return (
    <>
      <Topbar title="Alerts" subtitle="Threshold-violation alerts generated by the rule engine" />

      <div className="p-6 space-y-4">
        <div className="flex items-center gap-2">
          {SEVERITY_FILTERS.map((s) => (
            <button
              key={s}
              onClick={() => setFilter(s)}
              className={[
                'px-3 py-1.5 rounded-md text-[12.5px] font-medium border transition-colors',
                filter === s
                  ? 'bg-rail-navy text-white border-rail-navy'
                  : 'bg-white text-rail-steel border-rail-line hover:border-rail-blue/40',
              ].join(' ')}
            >
              {s}
            </button>
          ))}
        </div>

        <div className="panel">
          <div className="panel-header">
            <p className="font-display font-medium text-[14px] text-rail-navy">Alerts</p>
            <span className="label-eyebrow">{alerts.length} record(s)</span>
          </div>
          <div className="overflow-x-auto">
            <table className="w-full text-[13px]">
              <thead>
                <tr className="text-left text-rail-steelLight border-b border-rail-line">
                  <th className="px-4 py-2.5 font-medium">Time</th>
                  <th className="px-4 py-2.5 font-medium">Route</th>
                  <th className="px-4 py-2.5 font-medium">Train</th>
                  <th className="px-4 py-2.5 font-medium">Metric</th>
                  <th className="px-4 py-2.5 font-medium">Peak (g)</th>
                  <th className="px-4 py-2.5 font-medium">Threshold (g)</th>
                  <th className="px-4 py-2.5 font-medium">Nearest KM</th>
                  <th className="px-4 py-2.5 font-medium">Severity</th>
                </tr>
              </thead>
              <tbody>
                {alerts.map((a) => (
                  <tr key={a.id} className="border-b border-rail-line last:border-0 hover:bg-rail-fog/60">
                    <td className="px-4 py-2.5 text-rail-steelLight font-mono text-[12px]">
                      {new Date(a.time).toLocaleString('en-IN')}
                    </td>
                    <td className="px-4 py-2.5 text-rail-navy font-medium">{a.route}</td>
                    <td className="px-4 py-2.5 font-mono text-rail-steel">{a.trainId}</td>
                    <td className="px-4 py-2.5 text-rail-steel capitalize">{a.metric}</td>
                    <td className="px-4 py-2.5 font-mono text-rail-steel">{a.peak.toFixed(1)}</td>
                    <td className="px-4 py-2.5 font-mono text-rail-steelLight">{a.threshold.toFixed(1)}</td>
                    <td className="px-4 py-2.5 font-mono text-rail-steelLight">
                      {a.nearestTrackFeatureKm != null ? `Km ${a.nearestTrackFeatureKm.toFixed(0)}` : '—'}
                    </td>
                    <td className="px-4 py-2.5"><SeverityBadge severity={a.severity} /></td>
                  </tr>
                ))}
                {alerts.length === 0 && !loading && (
                  <tr>
                    <td colSpan={8} className="px-4 py-8 text-center text-rail-steelLight">
                      No alerts for this filter.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </>
  )
}
